- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionServiceTest.java
- dces-drc-integration/src/test/resources/mappings/contributionsPutStubs.json
Updating ContributionServiceTest valid scenario test to match only a successfully formed body.
This means should any changes to process to form the json, it should break this test. As it should.
> Improve wiremock pattern matching

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/client/ContributionClient.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/maatapi/model/fdc/FdcGlobalUpdateResponse.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/FdcServiceTest.java
- dces-drc-integration/src/test/resources/mappings/fdcGetStubs.json
- dces-drc-integration/src/test/resources/mappings/fdcGlobalUpdateStubs.json
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-268)
Adding the Fdc Global Update endpoint to the main service. Tests have been made for both when the global update is successful, and failing. Mapping updated due to being unable to directly use fdc object ( naming issues ).
> DCES-268 - Add Fdc Global Update to service

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/maatapi/MaatApiClientFactory.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/FdcServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-318)
Changed the logic for the fdc service to log errors, and failures of the global update call, but continue on. 
This is due to there being other ways that valid FDCs can be made ready, not just with the global update. 
This will allow those kinds to be processed timely.
> DCES-318 Global Update non-blocking

- dces-drc-integration/build.gradle
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/client/TestDataClient.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/model/external/ConcorContributionStatus.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/model/external/UpdateConcorContributionStatusRequest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionIntegrationTest.java
* Modified `build.gradle` to allow Lombok in both `test` and `integrationTest` tests
* Added simple `TestDataClient` interface for generated client to the DCES test-data services in maat-api
* Added model (dto) classes for the update-status test-data service
* Added a (disabled for now) integration test method (will be extended to a full test case in time)
* Changed the URL prefix for test-data services in the maat-cd-api.
[As a Developer I want to add Test Scenarios for the Contribution Use Cases for the Service](https://dsdmoj.atlassian.net/browse/DCES-333)
These are some pre-requisite changes to get up-and-running with DCES-333 and its sub-tickets (e.g. DCES-349).
> DCES-333 pre-requisites for first functional tests

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/client/TestDataClient.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/model/external/ConcorContributionResponseDTO.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/ContributionProcessSpy.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/SpyFactory.java
- dces-drc-integration/src/integrationTest/resources/application.yaml
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/client/ContributionClient.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
[DCES-349](https://dsdmoj.atlassian.net/browse/DCES-349)
Integration test that checks that `ContributionService#processDailyFiles()` does the expected orchestration: calling the maat-cd-api before and after calling the third-party DRC.
See the Jira ticket for more details, but for the implementation, the Mockito spying has been moved into a separate class (`ContributionProcessSpy`) to allow it to be reused in multiple integration tests. It is expected a similar `FdcProcessSpy` class will be created to "track" execution of the FDC integration tests.
[DCES-349]: https://dsdmoj.atlassian.net/browse/DCES-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-349 updated testdata client, and first integration test

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/client/TestDataClient.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/ContributionProcessSpy.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/client/ContributionClient.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/maatapi/MaatApiWebClientFactory.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/test/resources/mappings/contributionsLogMessagesStubs.json
- dces-drc-integration/src/test/resources/mappings/contributionsPutStubs.json
- dces-drc-integration/src/test/resources/mappings/fdcLogMessagesStubs.json
- dces-drc-integration/src/test/resources/mappings/fdcPutStubs.json
[DCES-379](https://dsdmoj.atlassian.net/browse/DCES-379) Change contribution_file client methods to accept Integer (not Boolean)
- Clear up confusion of having both HTTP status error code and a Boolean response body which is only sent with HTTP status 200
- Change the clients to reflect the new return type and error handling
- Update the WireMock JSON mappings to reflect the changed protocol
- Use the contribution_file ID in the integration tests
- Minor: Fix the TestDataClient to use the updated URL prefix
- Minor: Increase the read timeout for maatapi clients to 90 seconds as 30 seconds was insufficient for integration tests (on development env)
- Minor: Catch other exceptions that the maatapi clients can throw
Needed to be able to write some of the tests like DCES-354 and DCES-357, …
> DCES-379 Change contribution_file client methods to accept Integer return value (not Boolean)

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/client/TestDataClient.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/model/external/ContributionFileErrorResponse.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/model/external/ContributionFileResponse.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/ContributionProcessSpy.java
Improve Javadoc and method naming for integration tests
- Add Javadoc to contribution integration tests to describe the test case
- Add Javadoc @see link to the Jira ticket that specifies the test
- Rename contribution integration test methods to more have meaningful "given-when-then" names
- Refactor test implementations to more obviously follow the Javadoc and "given-when-then" order, and also to use the new contribution-file maat-api endpoints that were not available before
- Add the client side of the new contribution-file maat-api endpoings, including new DTO response model objects
- Simplified the spy class to only keep track of things that the spies record; other data can be kept track of by the test method itself
Comment out a couple of failing assertions
_Note I initially went …
> Document and rename integration tests

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/DrcLoggingIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/ContributionProcessSpy.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/DrcLoggingProcessSpy.java
[DCES-352](https://dsdmoj.atlassian.net/browse/DCES-352) Add integration test for unprocessed ACTIVE concor_contribution
- Rename the `instrument*` methods to `trace*` in the `*ProcessSpy` classes
- Make the `trace*` methods chainable (which maked sense in a `Builder` class)
- Update the tests that consume the `*ProcessSpy` classes
- Add a new test that an unprocessed ACTIVE concor_contribution is not included in the contribution file, and that its status is not changed to SENT
[DCES-352]: https://dsdmoj.atlassian.net/browse/DCES-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-352 Add integration test for unprocessed ACTIVE concor_contribution

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcTestDataCreatorService.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/FdcProcessSpy.java
[DCES-360](https://dsdmoj.atlassian.net/browse/DCES-360) Add negative integration test for fdc_contribution status
- Fix minor typo in test data creation service exception message
- Re-order member variables and methods in FDC spy (to match call order)
- Add new integration test to check SENT fdc-contributions are not processed
[DCES-360]: https://dsdmoj.atlassian.net/browse/DCES-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-360 Add negative integration test for fdc_contribution status

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcIntegrationTest.java
[DCES-361](https://dsdmoj.atlassian.net/browse/DCES-361) Add FDC integration test for DRC processing failure
- Add integration test for when FDC contributions fail to process with the DRC synchronously
- Refactor to Java 17 the 'legacy/POC' integration tests
- Rename the previous integration test to more sensible name
[DCES-361]: https://dsdmoj.atlassian.net/browse/DCES-361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-361 Add FDC integration test for DRC processing failure

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionLoggingIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcLoggingIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/ContributionLoggingProcessSpy.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/FdcLoggingProcessSpy.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/SpyFactory.java
[DCES-362](https://dsdmoj.atlassian.net/browse/DCES-362) [DCES-363](https://dsdmoj.atlassian.net/browse/DCES-363) Add FDC logging integration tests
- Add FDC integration tests for asynchronous DRC updates (logging)
- Rename `DrcLogging*` test and spy to `ContributionLogging*`
- Add `FdcLogging*` spy for the FDC logging test
- Improve Javadoc as per review comment in `FdcIntegrationTest#givenRequestedFdcContributions_whenProcessDailyFilesFailsToSend_thenTheirStatusIsNotUpdated`
- Move `getContributionFileErrorOptional` method into `SpyFactory` as a common utility method
[DCES-362]: https://dsdmoj.atlassian.net/browse/DCES-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCES-363]: …
> DCES-362 DCES-363 Add FDC logging integration tests

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/client/TestDataClient.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcTestDataCreatorService.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcTestDataCreatorServiceTest.java
Use the MAAT API's existing PATCH endpoint to update SOD (Sentence Order Date) to null (to be used in delayed pickup tests).
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-421)
Use the MAAT API's existing PATCH endpoint to update SOD to null (to be used in delayed pickup tests). This is necessary because the PUT endpoint ignores all null values.
> DCES-421: Enable SOD update to null

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcTestDataCreatorService.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcTestDataCreatorServiceTest.java
[DCES-411](https://dsdmoj.atlassian.net/browse/DCES-411) [DCES-412](https://dsdmoj.atlassian.net/browse/DCES-412) Negative tests with prev FDC
Additional fixes to tests:
- Add `@Disabled` to test that should currently be skipped (`FdcIntegrationTest.givenSomeFastTrackFdcContributionsWithNullSOD_whenProcessDailyFilesRuns_thenTheyAreNotQueriedNotSentNorInCreatedFile()`)
- Change to use PATCH to update SOD was not propagated into the test-data-creator tests
See also #70 (which somehow got confused about the merge direction).
[DCES-411]: https://dsdmoj.atlassian.net/browse/DCES-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCES-412]: https://dsdmoj.atlassian.net/browse/DCES-412?atlOrigin=eyJpIjoiNWRkNT …
> DCES-411 DCES-412 Negative tests with prev FDC (and fix tests)

- dces-drc-integration/build.gradle
[DCES-444](https://dsdmoj.atlassian.net/browse/DCES-444) Fix sentry dependencies
- Only need one of platform BOM or `dependencyManagement` section
- Use `versions` property only, rather than copying the version value
- Versions are constrained by the BOM, so no need for explicit dependency versions
- For Spring Boot 3.x, use `sentry-spring-boot-starter-jakarta` (not `sentry-spring-boot-starter`)
[DCES-444]: https://dsdmoj.atlassian.net/browse/DCES-444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-444 Fix sentry dependencies

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/config/DrcApiWebClientConfiguration.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/maatapi/MaatApiWebClientFactory.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/client/DrcApiClientTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/config/DrcApiWebClientConfigurationTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/controller/AckFromDrcControllerTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/maatapi/MaatApiWebClientFactoryTest.java
[DCES-505](https://dsdmoj.atlassian.net/browse/DCES-505) Use ISO 8601 date strings in JSON API calls to DRC
- Avoid `WebClient.builder()`, prefer injected `WebClient.Builder` instance from Spring Boot (which will be auto-configured).
- Avoid `new ObjectMapper()`, prefer injected `ObjectMapper` instance from Spring Boot (which will be auto-configured).
- Configure Jackson serialization to serialize `XMLGregorianCalendar` using `toString()`.
[DCES-505]: https://dsdmoj.atlassian.net/browse/DCES-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-505 Use ISO 8601 date strings in JSON API calls to DRC

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/config/Feature.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/config/JacksonConfiguration.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/controller/StubAckFromDrcController.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/controller/TempTestController.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/model/ConcorContributionReqForDrc.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/model/FdcReqForDrc.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/config/FeatureAllFalseTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/config/FeatureAllTrueTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/config/JacksonConfigurationTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionServiceTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/FdcServiceTest.java
- helm_deploy/laa-dces-drc-integration/templates/deployment.yaml
[DCES-525](https://dsdmoj.atlassian.net/browse/DCES-525) Add feature flag to prevent sending to DRC and updating status.
- Add feature flag implementation based on `FEATURE_[A-Z]*` environment variables imported as the secret keys from a K8s external secret and a `ConfigurationProperties` context bean.
- Change the K8s deployment YAML to expose this optional secret into the pod/container environment (in addition to existing variables).
- Add the DTO classes to the Jackson configuration for NON_NULL JSON serialization and simplified the DTO classes' constructor null checks.
- Make the StubAckFromDrcController and TempTestController controller classes be conditional on feature flags (endpoints can be disabled).
- Change the processDailyFiles methods to prevent "outgoing" data sent to the …
> DCES-525 Add feature flag to prevent sending to DRC and updating status.

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/FdcServiceTest.java
Make feature flag also disable global FDC update
- Following on from [DCES-525](https://dsdmoj.atlassian.net/browse/DCES-525), discussed with Tariq and agreed that the `feature.outgoing-isolated` feature flag should also disable the global FDC update.
[DCES-525]: https://dsdmoj.atlassian.net/browse/DCES-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make feature flag also disable global FDC update

- dces-drc-integration/build.gradle
Quick redo of sonar exclusions to remove tests and temporary controllers to stop them affecting metrics.
Updating the wiremock version.
> Sonar Exclusions Update

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/model/ConcorContributionAckFromDrc.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/model/FdcAckFromDrc.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/model/ProblemDetails.java
[DCES-534](https://dsdmoj.atlassian.net/browse/DCES-534) Change incoming APIs to use ProblemDetail report
Normally only the `detail` member (human-readable description of the issue) of the `ProblemDetail` is stored in the MAAT DB's `CONTRIBUTION_FILE_ERRORS.ERROR_TEXT` column. However, the other members could be stored in the DRC integration's own database, logged by the application to help troubleshooting, or used for making decisions on how to handle error reports.
[DCES-534]: https://dsdmoj.atlassian.net/browse/DCES-534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-534 Change incoming APIs to use ProblemDetail report

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/client/ContributionClientTest.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/client/ContributionClient.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionServiceTest.java
- dces-drc-integration/src/test/resources/mappings/contributionsGetStubs.json
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-591)
Fix the broken pagination in MAAT API calls where the request parameter name was wrong.
Added integration test for the same.
> Dces-591 fix pagination

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/utils/RequestSpecificationBuilder.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/client/DrcClient.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/config/DrcApiWebClientConfiguration.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/config/FeatureProperties.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/config/MaatApiWebClientConfiguration.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/config/ServicesProperties.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/controller/TempTestController.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/main/resources/application.yaml
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/client/DrcApiClientTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/config/DrcApiWebClientConfigurationTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/config/FeaturePropertiesAllFalseTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/config/FeaturePropertiesAllTrueTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/config/MaatApiWebClientConfigurationTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/config/ServicesPropertiesTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionServiceTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/FdcServiceTest.java
[DCES-584](https://dsdmoj.atlassian.net/browse/DCES-584) Add OAuth2 to the DRC client
- Rename `@ConfigurationProperties` classes to `-Properties` for consistency.
- Add `@Qualifier` to usages of the two `WebClient` context beans to make their usage unambiguous (it likely worked before because of parameter names being default qualifiers)
- Add simple client_credentials OAuth2 configuration to the `drcApiWebClient` bean.
Currently the OAuth2 configuration on the DRC API is not enabled, and the configuration parameters (`DRC_API_OAUTH_*` environment variables) are all undefined. However, they could easily be set in `config-variables`.
[DCES-584]: https://dsdmoj.atlassian.net/browse/DCES-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> DCES-584 Add OAuth2 to the DRC client

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/config/DrcApiWebClientConfiguration.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/config/MaatApiWebClientConfiguration.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/client/ContributionClientTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/config/MaatApiWebClientConfigurationTest.java
OAuth changes to make drc-client work from non-request context
- Default manager tries to access the principal from the request, which doesn't work in a cron scheduled job.
> OAuth changes to make drc-client work from non-request context

- dces-drc-integration/src/main/resources/schemas/concorContribution.opt.schema.json
Removed required attribute from the correspondence.letter.id property, as we have found (likely historical) examples that omit the id.
> Remove required attribute from letter id property

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/MigrationService.java
Changing method used to populate the migration entity to properly save the error message.
The validation messages being sent back were being lost.
> DCES-Advantis-Migration-Error-Handling

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/client/DrcClient.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/MigrationService.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionServiceTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/FdcServiceTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-689)
Adding persistance of the response to the sendToDrc calls. Basic String in order to persist the whole response, regardless of type/formatting.
> DCES-689-200-Response-Persistence

- .circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-714)
We have experienced failing deployments because of vestigial settings (such as environment variables that depend on secrets) not being deleted when we deploy new versions.
To avoid this, added force:true as a parameter to helm upgrade command so that the existing settings are removed and recreated (if needed) by every deployment. 
> Dces 714 force helm deployment refresh

- README.md
- helm_deploy/laa-dces-drc-integration/templates/ingress-mTLS.yaml
- helm_deploy/laa-dces-drc-integration/templates/ingress.yaml
[DCES-706](https://dsdmoj.atlassian.net/browse/DCES-706) Change ingress enabled to enable.mtls/nonMtls
So we can enable/disable the two ingress endpoints independently, without clashing with the previous `privateIngress.enabled` value. A corresponding change was made to all the AWS Secrets to revert back so that `privateIngress.enabled` has a value, and to add the new values `privateIngress.enable.mtls` and `privateIngress.enable.nonMtls`, which will be used in future.
At some future time, when this change has been promoted into all environments, then the value `privateIngress.enabled` can be removed from the AWS Secrets.
[DCES-706]: https://dsdmoj.atlassian.net/browse/DCES-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
> DCES-706 Change ingress enabled to enable.mtls/nonMtls
