- helm_deploy/laa-dces-drc-integration/templates/NOTES.txt
- helm_deploy/laa-dces-drc-integration/templates/_environment.tpl
- helm_deploy/laa-dces-drc-integration/templates/_helpers.tpl
- helm_deploy/laa-dces-drc-integration/templates/deployment.yaml
- helm_deploy/laa-dces-drc-integration/templates/hpa.yaml
- helm_deploy/laa-dces-drc-integration/templates/ingress.yaml
- helm_deploy/laa-dces-drc-integration/templates/networkpolicy.yaml
- helm_deploy/laa-dces-drc-integration/templates/service.yaml
- helm_deploy/laa-dces-drc-integration/templates/serviceaccount.yaml
- helm_deploy/laa-dces-drc-integration/templates/servicemonitor.yaml
- helm_deploy/laa-dces-drc-integration/templates/tests/test-connection.yaml
Updating helm files to correct namespace.
> Update Helm Files

- dces-drc-integration/build.gradle
- dces-drc-integration/src/main/resources/schemas/contributions.xsd
- dces-drc-integration/src/main/resources/schemas/fdc.xsd
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-169)
Adding JaxB conversion from XML to objects. 
> DCES-169-Setup-JaxB

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
Updating handling to use correct id list.
> Correct the ID being used.

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/client/ContributionClient.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/maatapi/model/fdc/FdcContributionEntry.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/maatapi/model/fdc/FdcContributionsResponse.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/model/ContributionPutRequest.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/utils/ContributionsMapperUtils.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/utils/FdcMapperUtils.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/utils/MapperUtils.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionServiceTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/FdcServiceTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/utils/FdcMapperUtilsTests.java
- dces-drc-integration/src/test/resources/mappings/fdcGetStubs.json
Adding getFdc functionality.
Changing all uses of Date to LocalDate for mapping. Tests added.
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-198)
> DCES-198-Get-Fdc-Entries

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/client/ContributionClient.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/model/ContributionUpdateRequest.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/model/FdcUpdateRequest.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/model/UpdateRequest.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/utils/ContributionsMapperUtils.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/utils/FdcMapperUtils.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/utils/MapperUtils.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionServiceTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/FdcServiceTest.java
- dces-drc-integration/src/test/resources/mappings/contributionsPutStubs.json
- dces-drc-integration/src/test/resources/mappings/fdcPutStubs.json
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-200)
> DCES-200 Add FDC Atomic Update Integration

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionIntegrationTest.java
[DCES-351](https://dsdmoj.atlassian.net/browse/DCES-351) Integration test for replaced contributions
- Originally written by Vid, but updated for service changes
- Test spec says to verify that contribution_file is created. However, that only happens if there are other ACTIVE concor_contribution rows. Unfortunately the tests interact, so it's possible there will not be
Depends on #46, which should be merged before this
[DCES-351]: https://dsdmoj.atlassian.net/browse/DCES-351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-351 Integration test for replaced contributions

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/DrcLoggingIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/ContributionProcessSpy.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/DrcLoggingProcessSpy.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/SpyFactory.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
[DCES-354](https://dsdmoj.atlassian.net/browse/DCES-354) Positive DRC logging response integration test
- Added a new integration test and corresponding spy for the DRC logging endpoint
- Moved utility method to updateStatus into SpyFactory utility class
- Changed `WebClientException` to `WebClientResponseException` in services
[DCES-354]: https://dsdmoj.atlassian.net/browse/DCES-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-354 Positive DRC logging integration test

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/DrcLoggingIntegrationTest.java
[DCES-392](https://dsdmoj.atlassian.net/browse/DCES-392) Fix DCES tests (received files and modified date/user)
Depends on ministryofjustice/laa-maat-court-data-api#1004
[DCES-392]: https://dsdmoj.atlassian.net/browse/DCES-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-392 Fix DCES tests (received files and modified date/user)

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcTestDataCreatorService.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/FdcProcessSpy.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/SpyFactory.java
[DCES-357](https://dsdmoj.atlassian.net/browse/DCES-357) Add positive FDC integration tests
- Refactor existing [DCES-356](https://dsdmoj.atlassian.net/browse/DCES-356) into 'given', and helper method for 'when'/'then'
- Add integration tests for [DCES-357](https://dsdmoj.atlassian.net/browse/DCES-357), [DCES-358](https://dsdmoj.atlassian.net/browse/DCES-358), [DCES-359](https://dsdmoj.atlassian.net/browse/DCES-359) using said helper
- Minor changes to formatting in `Spy` and `TestData` classes
[DCES-357]: https://dsdmoj.atlassian.net/browse/DCES-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCES-356]: https://dsdmoj.atlassian.net/browse/DCES-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
> DCES-357 Add positive FDC integration tests

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcLoggingIntegrationTest.java
Disable failing tests due to oauth scope
> Disable failing tests due to oauth scope

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcIntegrationTest.java
[Link to story 1](https://dsdmoj.atlassian.net/browse/DCES-407)
[Link to story 2](https://dsdmoj.atlassian.net/browse/DCES-408)
DCES-407: Create Negative Test Scenarios for FDC Service - Crown Court Outcome doesn't exist (Delayed pickup)
DCES-408: Create Negative Test Scenarios for FDC Service - Crown Court Outcome doesn't exist (Fast tracked pickup)
Also refactored some previous methods to use the shared code in the new method runProcessDailyFilesAndCheckResults.
All these tests are currently disabled, pending creation of /assessment/ handler (use locally running MAAT API to test them).
> DCES-407 and DCES-408 plus some refactoring

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcIntegrationTest.java
[Link to story 1](https://dsdmoj.atlassian.net/browse/DCES-409)
[Link to story 2](https://dsdmoj.atlassian.net/browse/DCES-410)
Describe what you did and why.
Added negative test cases as follows:
DCES-409: Create Negative Test Scenarios for FDC Service - FDC Item doesn't exist (Delayed pickup)
DCES-410: Create Negative Test Scenarios for FDC Service - FDC Item doesn't exist (Fast Track pickup)
> Dces 409 410 negative test fdc items

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
[DCES-234](https://dsdmoj.atlassian.net/browse/DCES-234) Improve logging, add file ID list
- Clean up code style / format a bit
- Add log line for contribution-file's list of contribution-ids (see my comments)
- Clean up other log messages
[DCES-234]: https://dsdmoj.atlassian.net/browse/DCES-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-234 Improve logging, add file ID list

- .circleci/config.yml
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcIntegrationTest.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcTestDataCreatorService.java
- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/service/FdcTestDataCreatorServiceTest.java
- Update code style
> ***`Note`*** because of indentation changes, the diff is best compared with
> `--ignore-all-spaces` in git or **Hide whitespace** on GitHub
- Uncomment some test assertions (two lines marked in the diff by me)
- Additionally add extra timeout for no output in circleCI step for int tests (timed out with default of 10 mins - see [before](https://app.circleci.com/pipelines/github/ministryofjustice/laa-dces-drc-integration/407/workflows/9d86af93-f249-4e73-94be-b731ee2568a3/jobs/3155/parallel-runs/0/steps/0-111) and [after](https://app.circleci.com/pipelines/github/ministryofjustice/laa-dces-drc-integration/408/workflows/9b6c84a3-aabf-471c-9a7c-37cadaf1929c/jobs/3164/parallel-runs/0/steps/0-111))
> Update code style, uncomment some test assertions

- .github/CODEOWNERS
> Set CODEOWNERS to DCES

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/controller/DcesDrcErrorController.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/controller/StubAckFromDrcController.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/handler/GlobalExceptionHandler.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/controller/AckFromDrcControllerTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/controller/DcesDrcErrorControllerTest.java
[DCES-506](https://dsdmoj.atlassian.net/browse/DCES-506) Make errors use problem details with traceid, validationErrors
[DCES-506]: https://dsdmoj.atlassian.net/browse/DCES-506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCES-506 Make errors use problem details with traceid, validationErrors

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/config/Feature.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
Add logging of JSON request payload when sending to DRC is disabled
> Add logging of JSON request payload when sending to DRC is disabled

- dces-drc-integration/src/main/resources/schemas/contributionsLine.xsd
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/client/DrcApiClientTest.java
Changing int to Integer for ids and the breathing space amount.
Changing a large number of things to decimal as they're stored as NUMBER(n,2), which byte/int/etc wouldn't handle.
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-537)
Describe what you did and why.
> DCES-537-xsd fix

- dces-drc-integration/src/main/resources/schemas/contributionsLine.xsd
Adding a couple of missed value type changes.
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-537)
> DCES-537 Xsd Fixes

- dces-drc-integration/src/main/resources/schemas/concorContribution.opt.schema.json
- dces-drc-integration/src/main/resources/schemas/fdcContribution.opt.schema.json
Add JSON schema files to GitHub
> Add JSON schema files to GitHub

- dces-drc-integration/build.gradle
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/AnonymisingDataService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/utils/DateConvertor.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/DcesDrcIntegrationApplicationTests.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/AnonymisingDataServiceTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionServiceTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/utils/DateConvertorTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-510)
AnonymisingData for Contribution data 
> OP-510 - AnonymisingData for Contribution

- dces-drc-integration/src/main/resources/schemas/concorContribution.opt.schema.json
- dces-drc-integration/src/main/resources/schemas/contributionsLine.xsd
Fixes more bugs in the XSD provided. 
Changes are reflected in the json schema.
> Contribution Structure Fixes

- dces-drc-integration/src/main/resources/schemas/concorContribution.opt.schema.json
- dces-drc-integration/src/main/resources/schemas/contributionsLine.xsd
Another change for the XSD to better mimic the output from the matrix code.
Added a missing "otherDescription" field, and a missed object.
> More xsd changes

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/datasource/model/CaseMigrationEntity.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/datasource/repository/CaseMigrationRepository.java
- dces-drc-integration/src/main/resources/db/migration/V1_0_6__migration_schema.sql
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-637)
Update due to info from further discussion on the structure of the migration data.
> DCES-637-Schema-Update

- dces-drc-integration/src/integrationTest/java/uk/gov/justice/laa/crime/dces/integration/testing/MigrationDbLoggingTest.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/datasource/model/CaseMigrationEntity.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/datasource/model/CaseMigrationPK.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/datasource/repository/CaseMigrationRepository.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/datasource/DatabaseServiceTest.java
Adding some quick tests and fixing the build.
The failures in the build are due to 2 503 responses from Maat API
> Fix Build and Add Tests

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/main/resources/schemas/concorContribution.opt.schema.json
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/ContributionServiceTest.java
Changing method used to populate the migration entity to properly save the error message.
This will log the error response sent by the endpoint.
> WebClient Error Message Storage

- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/service/FdcService.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/utils/ContributionsMapperUtils.java
- dces-drc-integration/src/main/java/uk/gov/justice/laa/crime/dces/integration/utils/FdcMapperUtils.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/service/FdcServiceTest.java
- dces-drc-integration/src/test/java/uk/gov/justice/laa/crime/dces/integration/utils/FdcMapperUtilsTests.java
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-692)
Fixing xml file header generation, removing TODO.
Fixing tests associated with the change.
> DCES-692 Xml File Header Generation

- README.md
[Link to story](https://dsdmoj.atlassian.net/browse/DCES-705)
Added basic instructions to installing and configuring was git-secrets in readme.
> added git-secrets to README.md

- dces-drc-integration/build.gradle
Updated Spring Boot dependencies.
> Update Spring Boot dependencies

- .circleci/config.yml
- .github/workflows/codeql-analysis.yml
- dces-drc-integration/Dockerfile
- dces-drc-integration/Dockerfile.int-test
- dces-drc-integration/build.gradle
- dces-drc-integration/gradle/wrapper/gradle-wrapper.properties
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-4186)
Upgraded service to Java 21.
> LASB-4186 - upgraded service to Java 21
